options = gaoptimset('PlotFcns',{@gaplotbestf},...
    'SelectionFcn',{@selectionroulette},'CrossoverFcn',{@crossoverscattered},...
    'PopulationSize',20,'Generations',100,'FitnessLimit',1e-5); %控制选项
[x fval reason] = ga(@myfun,1,options)